version: '2'
services:
  tor:
    image: bwstitt/tor
    expose:
      - "9050"
    volumes:
      - "./config/torrc:/etc/tor/torrc:ro"
      - "tor:/var/lib/tor"

  mainnet:
    image: bwstitt/zcash
    entrypoint: ["/bin/sh"]
    command: ["/zcashd-entrypoint.sh"]
    # use expose instead of ports to only listen on the Tor network
    ports:
      - "8233:8233/tcp"
    volumes:
      - "./config/mainnet.conf:/config/zcash.conf:ro"
      - "./zcash/zcashd-entrypoint.sh:/zcashd-entrypoint.sh:ro"
      - "mainnet:/home/zcash/.zcash"
      - "params:/home/zcash/.zcash-params"

volumes:
  mainnet: {}
  tor: {}
  params: {}
